account/urls.py
from django.urls import path
from . import views
from django.urls import include

app_name = "account"
urlpatterns = [
    path("login", views.user_login, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("edit", views.edit, name="edit"),
    path("api/v1/", include("account.api.v1.url")),
    path("api/v2/", include("djoser.urls.jwt")),  # migration  v1 to v2
]

blog/urls.py
from django.urls import path
from . import views
from django.urls import include

app_name = "blog"
urlpatterns = [
    path("detail/<slug:slug>", views.ArticleDetail.as_view(), name="detail"),
    path("post", views.post_list, name="post"),
    path("art/<int:pk>", views.category_detail, name="category"),
    path("search", views.search, name="search"),
    path("contact", views.contact, name="contact"),
    path("list", views.Article.as_view(), name="list"),
    path("home", views.HomePageRedirect.as_view(), name="home"),
    path("like", views.like, name="like"),
    path("api/v1/", include("blog.api.v1.urls")),
]

standblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls
from standblog import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("", include("account.urls")),
    path("", include("blog.urls")),
    path("", include("contact.urls")),
    path("api_auth", include("rest_framework.urls")),
    # path('api_docus/',include_docs_urls(title='API')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
{% load static %}
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="social-icons">
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Behance</a></li>
                    <li><a href="#">Linkedin</a></li>
                    <li><a href="#">Dribbble</a></li>
                </ul>
            </div>
            <div class="col-lg-12">
                <div class="copyright-text">
                    <p>Copyright 2020 Stand Blog Co.

                        | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/includes/header.html
{% load static %}

<header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="index.html"><h2>Stand Blog<em>.</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="index.html">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="about.html">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:post' %}">Blog Entries</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="post-details.html">Post Details</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="contact.html">Contact Us</a>

              </li>
               <li class="nav-item">
                   <div>
                   {% if request.user.is_authenticated %}
                       {% if user.profile.image %}
                         <span class="avatar avatar-image"><img src="{{ user.profile.image.url }}" width="25px" height="25px"></span>
                       {% endif %}
                   <a class="nav-link" href="">{{ request.user.fist_name}}</a>
                   <a class="nav-link" href ='{% url 'account:logout' %}'><span>Logout</span></a>
                   </div>
                   {% else %}
                   <a class="nav-link" href="{% url 'account:login'  %}">Login</a>
                   {% endif %}
               </li>
               <li class="nav-item">
                 <a class="nav-link" href="{% url 'account:register' %}">Register</a>
               </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

templates/includes/refrence_footer.html
{% load static %}

<!-- Bootstrap core JavaScript -->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static "js/custom.js" %}"></script>
    <script src="{% static "js/owl.js" %}"></script>
    <script src="{% static "js/slick.js" %}"></script>
    <script src="{% static "js/isotope.js" %}"></script>
    <script src="{% static "js/accordions.js" %}"></script>
    <script src="{% static "js/like.js" %}"></script></script>

    <script language = "text/Javascript">
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>

templates/includes/refrence_html.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="TemplateMo">
<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap"
      rel="stylesheet">

<title>Stand CSS Blog by TemplateMo</title>

<!-- Bootstrap core CSS -->
<link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">


<!-- Additional CSS Files -->
<link rel="stylesheet" href="{% static "css/fontawesome.css" %}">
<link rel="stylesheet" href="{% static "css/templatemo-stand-blog.css" %}">
<link rel="stylesheet" href="{% static "css/owl.css" %}">
<!--

TemplateMo 551 Stand Blog

https://templatemo.com/tm-551-stand-blog

-->

templates/includes/sideBar.html
{% load static %}
<div class="col-lg-4">
    <div class="sidebar">
        <div class="row">
            <div class="col-lg-12">
                <div class="sidebar-item search">
                    <form id="search_form" name="gs" method="GET" action="{% url 'blog:search' %}">
                        <input type="text" name="q" class="searchText" placeholder="type to search..."
                               autocomplete="on">
                    </form>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item recent-posts">
                    <div class="sidebar-heading">
                        <h2>Recent Posts</h2>
                    </div>
                    <div class="content">
                        <ul>
                            {% for post in recent_posts%}
                                <li><a href={{ post.get_absolute.url }}>
                                    <h5>{{ post.title }}</h5>
                                    <span>{{ post.created }}</span>
                                </a></li>

                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item categories">
                    <div class="sidebar-heading">
                        <h2>Categories</h2>
                    </div>
                    <div class="content">
                        <ul>
                            {% for category in category %}
                                <li><a href="#">{{ category.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item tags">
                    <div class="sidebar-heading">
                        <h2>Tag Clouds</h2>
                    </div>
                    <div class="content">
                        <ul>
                            {# {{ name => kilid dict minevisim }} #}
                            <li><a href="#">Lifestyle</a></li>
                            <li><a href="#">Creative</a></li>
                            <li><a href="#">HTML5</a></li>
                            <li><a href="#">Inspiration</a></li>
                            <li><a href="#">Motivation</a></li>
                            <li><a href="#">PSD</a></li>
                            <li><a href="#">Responsive</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>