blog/api/v1/urls.py
from .views import (
    post_detail,
    PostList,
    PostDetail,
    PostList1,
    PostViewSet,
    CategoryViewSet,
)
from django.urls import path
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register("post_set", PostViewSet)  # 1.kodom viewset 2.basename = name
router.register("category", CategoryViewSet)
app_name = "api_v1"
urlpatterns = [
    path("post1/", PostList.as_view(), name="blog_list"),
    path("post/detail/<slug:slug>", PostDetail.as_view(), name="detail"),
    path("post2/", PostList1.as_view(), name="blog_list1"),
    path(
        "setview/",
        PostViewSet.as_view({"get": "list", "post": "create"}),
        name="setview1",
    ),  # in get = method list
    path(
        "setview/<slug:slug>",
        PostViewSet.as_view({"get": "retrieve", "put": "update", "delete": "destroy"}),
        name="setview2",
    ),
]
urlpatterns += router.urls

blog/urls.py
from django.urls import path
from . import views
from django.urls import include

app_name = "blog"
urlpatterns = [
    path("detail/<slug:slug>", views.ArticleDetail.as_view(), name="detail"),
    path("post", views.post_list, name="post"),
    path("art/<int:pk>", views.category_detail, name="category"),
    path("search", views.search, name="search"),
    path("contact", views.contact, name="contact"),
    path("list", views.Article.as_view(), name="list"),
    path("home", views.HomePageRedirect.as_view(), name="home"),
    path("like", views.like, name="like"),
    path("api/v1/", include("blog.api.v1.urls")),
]

contact/urls.py
from django.urls import path
from . import views

app_name = "contact"
urlpatterns = [
    path("contact", views.contact, name="contact"),
]

standblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls
from standblog import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("", include("account.urls")),
    path("", include("blog.urls")),
    path("", include("contact.urls")),
    path("api_auth", include("rest_framework.urls")),
    # path('api_docus/',include_docs_urls(title='API')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from .models import Message


# tamrin
class ConcatForm(forms.Form):
    year_choises = ["1991", "2000", "2011", "2012", "2013", "2014", "2015", "2016"]
    birthday = forms.DateField(
        widget=forms.SelectDateWidget(
            years=year_choises, attrs={"class": "form-control"}
        )
    )
    text = forms.CharField(label="text)")

    def clean_text(
        self,
    ):  # brary field khas shart bezarim bade clean esm field migozarim

        text = self.cleaned_data.get("text")  # method get
        if text == "":
            raise ValidationError("text is empty", code="empty")  # in code mesl klid
        return text  # bayad bashe baray marbot be field khas


# class MessageForm(forms.Form):
# title = forms.CharField(label='message')
# text = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
# email = forms.EmailField(label='email')


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message  # yani az kodam model
        fields = "__all__"  # che field haie
        # exclude =('date')  #hame field ha be joz kodam vaghti in bashe nabayad field bashe
        # baray style dadan ya mitavanim az ketabkhane  django-widget-tweaks
        widgets = {
            "text": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter your message"}
            )
        }

blog/api/v1/views.py
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .serializers import PostSerializer, CategorySerializer
from ...models import Post, Category
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from rest_framework.generics import (
    ListAPIView,
    ListCreateAPIView,
    CreateAPIView,
    RetrieveAPIView,
    UpdateAPIView,
    DestroyAPIView,
    GenericAPIView,
)
from rest_framework import mixins
from rest_framework import viewsets
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters
from .page import DefaultPagination

"""@api_view(['GET', 'POST'])
@permission_classes((IsAuthenticated, ))
def post_list(request):
    if request.method == 'GET':
        posts = Post.objects.all()
        serializer = PostSerializer(posts, many=True)  # gharare koli item dashte bashe
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = PostSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)"""


@api_view(["GET", "PUT", "DELETE"])
def post_detail(request, slug):
    post = Post.objects.get(slug=slug)
    if request.method == "GET":
        serializer = PostSerializer(post)
        return Response(serializer.data)
    elif request.method == "PUT":  # update etelat
        serializer = PostSerializer(post, data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
    elif request.method == "DELETE":
        post.delete()
        return Response(status=204)


class PostList1(ListCreateAPIView):  # ham get ham post
    permission_classes = (IsAuthenticated,)
    serializer_class = PostSerializer  # form tamiz tare
    queryset = Post.objects.all()


"""class PostList1(GenericAPIView,mixins.ListModelMixin,mixins.CreateModelMixin):
    permission_classes = (IsAuthenticated,)
    serializer_class = PostSerializer  # form tamiz tare
    queryset = Post.objects.all()
    def get(self,request,*args,**kwargs):
        return self.list(request,*args,**kwargs)
    def post(self,request,*args,**kwargs):
        return self.create(request,*args,**kwargs)"""

"""bayad queryset befrestim
class PostList1(GenericAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = PostSerializer  # form tamiz tare
    queryset = Post.objects.all()


    def get(self, request):
        queryset = self.get_queryset()
        serializer =serializer_class(queryset, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)"""


class PostList(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = PostSerializer  # form tamiz tare

    def get(self, request):
        posts = Post.objects.all()
        serializer = PostSerializer(posts, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = PostSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

    def delete(self, request, slug):
        post = Post.objects.get(slug=slug)
        post.delete()
        return Response(status=204)


# ghabeliat update dare RetrieveUpdateAPIView
class PostDetail2(RetrieveAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = PostSerializer
    queryset = (
        Post.objects.all()
    )  # همه پست‌ها را می‌دهد و فیلتر کردن بر اساس slug خودکار انجام می‌شود
    lookup_field = "slug"


class PostDetail1(
    GenericAPIView,
    mixins.RetrieveModelMixin,
    mixins.UpdateModelMixin,
    mixins.DestroyModelMixin,
):
    permission_classes = (IsAuthenticated,)
    serializer_class = PostSerializer
    queryset = Post.objects.all()
    lookup_field = "slug"  # yani donbal che objectiam

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


class PostDetail(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = PostSerializer

    def get(self, request, slug):
        post = Post.objects.get(slug=slug)
        serializer = self.serializer_class(post)
        return Response(serializer.data)

    def put(self, request, slug):
        post = Post.objects.get(slug=slug)
        serializer = self.serializer_class(post, data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

    def delete(self, request, slug):
        post = Post.objects.get(slug=slug)
        post.delete()
        return Response(status=204)


# viewset
"""class PostViewSet(viewsets.ViewSet):
    permission_classes = (IsAuthenticated, )
    serializer_class = PostSerializer
    queryset = Post.objects.all()
    #list post
    def list(self,request,*args,**kwargs):
        serializer = self.serializer_class(self.queryset, many=True)
        return Response(serializer.data)
    #detail post
    def retrieve(self,request,slug):
        post = Post.objects.get(slug=slug)
        serializer = self.serializer_class(post)
        return Response(serializer.data)

    def create(self,request,*args,**kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

    def destroy(self,request,slug):
        post = Post.objects.get(slug=slug)
        post.delete()

        return Response(status=204)
    def update(self,request,slug):
        post = Post.objects.get(slug=slug)
        serializer = self.serializer_class(post, data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()"""


class PostViewSet(viewsets.ModelViewSet):
    permission_classes = (IsAuthenticated,)
    serializer_class = PostSerializer
    queryset = Post.objects.all()
    filter_backends = [
        DjangoFilterBackend,
        filters.OrderingFilter,
        filters.SearchFilter,
    ]
    filterset_fields = ["category", "author"]
    search_fields = ["title"]
    ordering_fields = ["created"]
    pagination_class = DefaultPagination
    # yani ye mored ezafe
    # @action(detail=True, methods=['get'])
    # ef get_ok(self,request):
    #   return Response({'detail':'ok'})


class CategoryViewSet(viewsets.ModelViewSet):
    permission_classes = (IsAuthenticated,)
    serializer_class = CategorySerializer
    queryset = Category.objects.all()

blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Post, Comment, Message
from django.core.paginator import Paginator
from .forms import MessageForm
from django.http import HttpResponse
from django.views.generic.base import View, TemplateView, RedirectView
from django.views.generic.list import ListView
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST


# Create your views here.
def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)

    if request.method == "POST":
        body = request.POST.get("message")
        parent_id = request.POST.get("parent_id")

        # بررسی اگر parent_id خالی است، آن را به None تغییر دهیم
        if parent_id == "":
            parent_id = None
        # اگر parent_id
        # موجود باشد، آن را به شیء مربوطه تبدیل می‌کنیم
        parent_comment = None
        if parent_id:
            parent_comment = get_object_or_404(Comment, id=parent_id)

        # ایجاد کامنت جدید
        Comment.objects.create(
            comment=body, post=post, user=request.user, parent=parent_comment
        )

    return render(request, "blog/post-details.html", {"post": post})


def post_list(request):
    posts = Post.objects.all()
    page = request.GET.get("page")
    paginator = Paginator(posts, 3)
    object_list = paginator.get_page(page)
    return render(request, "blog/post_list.html", {"posts": object_list})


def category_detail(request, pk):
    category = get_object_or_404(Post, id=pk)
    article = category.article_set.all()
    return render(request, "blog/post_list.html", {"posts": article})


def search(request):
    query = request.GET.get("q")
    articles = Post.objects.filter(title__contains=query)
    page = request.GET.get("page")
    paginator = Paginator(articles, 3)
    object_list = paginator.get_page(page)
    # onaieke havie q riy bozorg hasas  icontaions hasas nist
    return render(
        request, "blog/post_list.html", {"posts": object_list}
    )  # mitavanim az 1 temlate estefade konim dar chand view vali bayad kilid yeki bashe


def contact(request):
    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            #     text = form.cleaned_data['text']
            # email = form.cleaned_data['email']
            # title = form.cleaned_data['title']
            # Message.objects.create(text=text, email=email, title=title)

            # mianbor
            form.save()

            return redirect("/")
        else:
            form = ContactForm(request.POST)  # error
    else:
        form = MessageForm()

    return render(request, "blog/contact.html", {"form": form})


@login_required
@require_POST
def like(request):
    post_id = request.POST.get("post_id")
    post = get_object_or_404(Post, id=post_id)
    liked = False
    if request.user in post.likes.all():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True
    return JsonResponse({"liked": liked, "like_count": post.likes.count()})


# class base view
class ListView(View):
    queryset = None
    template_name = None

    def get(self, request):
        return render(request, self.template_name, {"posts": self.queryset})


class Article(ListView):
    queryset = Post.objects.all()
    template_name = "blog/post_list.html"


# template view
class Article2(TemplateView):
    template_name = "blog/post_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["posts"] = Post.objects.all()
        return context


class HomePageRedirect(RedirectView):
    # baray adres
    # url = 'https://blog.csdn.net/'
    # az name estefade konim
    pattern_name = "blog:list"
    # permanent = 301
    # permanent = 302 = False
    # permanent = True
    # query_string = true ?name=hasti save
    query_string = False

    # adres khas
    def get_redirect_url(self, *args, **kwargs):
        return super().get_redirect_url(*args, **kwargs)


class ArticleDetail(DetailView):
    model = Post
    template_name = "blog/post-details.html"
    # context_object-name= name key


# article_dertail pishfarz khod class

# class PostList(ListView):#def pageinator
#   model = Post
#  template_name = "blog/post_list.html"
# context_object_name = name key in html
# page_

contact/views.py
from django.shortcuts import render


# Create your views here.
def contact(request):
    return render(request, "contact/contact.html")

blog/templates/blog/contact.html
{% extends 'base.html' %}
{% load static %}
<!-- Banner Ends Here -->
{% block content %}

    <section class="contact-us">
        <div class="container">
            <div class="row">

                <div class="col-lg-12">
                    <div class="down-contact">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="sidebar-item contact-form">
                                    <div class="sidebar-heading">
                                        <h2>Send us a message</h2>
                                    </div>
                                    <div class="content">
                                        <form id="contact" action="" method="post">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-md-6 col-sm-12">
                                                    {{ form }}
                                                </div>
                                                <div class="col-lg-12">
                                                    <fieldset>
                                                        <button type="submit" id="form-submit" class="main-button">Send
                                                            Message
                                                        </button>
                                                    </fieldset>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>

        <div class="col-lg-12">
            <div id="map">
                <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed"
                        width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </div>

        </div>
        </div>
    </section>
{% endblock %}

blog/templates/blog/post-details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="heading-page header-text">
        <section class="page-heading">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-content">
                            <h4>Article Details</h4>
                            <h2>{{ post.title }}</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Banner Ends Here -->

    <section class="blog-posts grid-system">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="blog-post">
                                    <div class="blog-thumb">
                                        <img src={{ post.image.url }} alt="">
                                    </div>
                                    <div class="down-content">
                                        <span>Lifestyle</span>
                                        <a href={{ post.get_absolute_url }}><h4>{{ post.title }}</h4></a>
                                        <ul class="post-info">
                                            <li><a href="#">{{ post.author.username }}</a></li>
                                            <li><a href="#">May 12, 2020</a></li>
                                            <li><a href="#">10 Comments</a></li>
                                        </ul>
                                        <p>
                                            {{ post.body }}
                                        </p>
                                        <p>You can browse different tags such as <a rel="nofollow"
                                                                                    href="https://templatemo.com/tag/multi-page"
                                                                                    target="_parent">multi-page</a>, <a
                                                rel="nofollow" href="https://templatemo.com/tag/resume"
                                                target="_parent">resume</a>, <a rel="nofollow"
                                                                                href="https://templatemo.com/tag/video"
                                                                                target="_parent">video</a>, etc. to see
                                            more CSS templates. Sed hendrerit rutrum arcu, non malesuada nisi. Sed id
                                            facilisis turpis. Donec justo elit, dapibus vel ultricies in, molestie sit
                                            amet risus. In nunc augue, rhoncus sed libero et, tincidunt tempor nisl.
                                            Donec egestas, quam eu rutrum ultrices, sapien ante posuere nisl, ac
                                            eleifend eros orci vel ante. Pellentesque vitae eleifend velit. Etiam
                                            blandit felis sollicitudin vestibulum feugiat.
                                            <br><br>Donec tincidunt leo nec magna gravida varius. Suspendisse felis
                                            orci, egestas ac sodales quis, venenatis et neque. Vivamus facilisis
                                            dignissim arcu et blandit. Maecenas finibus dui non pulvinar lacinia. Ut
                                            lacinia finibus lorem vel porttitor. Suspendisse et metus nec libero
                                            ultrices varius eget in risus. Cras id nibh at erat pulvinar malesuada et
                                            non ipsum. Suspendisse id ipsum leo.</p>
                                        <div class="post-options">
                                            <div class="row">
                                                <div class="col-6">
                                                    <a href="#"> <i class="fa fa-heart-o"></i></a>
                                                </div>
                                                <div class="col-6">
                                                    <ul class="post-share">
                                                        <li><i class="fa fa-share-alt"></i></li>
                                                        <li><a href="#">Facebook</a>,</li>
                                                        <li><a href="#"> Twitter</a></li>

                                                    </ul>
                                                    <!-- templates/post_detail.html -->
                                                    <button id="like-btn" data-post-id="{{ post.id }}">
                                                        {% if user in post.likes.all %}
                                                            ❤️
                                                        {% else %}
                                                            🤍
                                                        {% endif %}
                                                    </button>
                                                    <span id="like-count">{{ post.likes.count  }}</span>


                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="sidebar-item comments">
                                    <div class="sidebar-heading">
                                        <h2>4 comments</h2>
                                    </div>
                                    <div class="content">
                                        <ul>
                                            {% for comment in post.comments.all %}
                                                {% if comment.parent == None %}
                                                    <li>
                                                        <div class="author-thumb">
                                                            <img src="{% static 'images/comment-author-01.jpg' %}"
                                                                 alt="">
                                                        </div>
                                                        <div class="right-content">
                                                            <h4>{{ comment.user.username }}<span>{{ comment.created }}</span>
                                                            </h4>
                                                            <p>{{ comment.comment }}</p>
                                                            <button class="btn btn-block"
                                                                    onclick="set_value({{ comment.id }})">Reply
                                                            </button>
                                                        </div>
                                                    </li>
                                                    {% for reply in comment.replies.all %}
                                                        <li class="replied">
                                                            <div class="author-thumb">
                                                                <img src="{% static 'images/comment-author-02.jpg' %}"
                                                                     alt="">
                                                            </div>
                                                            <div class="right-content">
                                                                <h4>{{ reply.user.username }}<span>{{ reply.created }}</span>
                                                                </h4>
                                                                <p>{{ reply.comment }}</p>
                                                            </div>
                                                        </li>
                                                    {% endfor %}
                                                {% endif %}
                                            {% empty %}
                                                <p>No comments yet. Be the first to comment!</p>
                                                <!-- نمایش پیامی در صورت عدم وجود کامنت -->
                                            {% endfor %}

                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="sidebar-item submit-comment">
                                    <div class="sidebar-heading">
                                        <h2>Your comment</h2>
                                    </div>
                                    <div class="content">
                                        <form id="comment" action="#" method="post">
                                            {% csrf_token %}
                                            <input type="hidden" id='id1' name="parent_id" value="">
                                            <div class="row">
                                                <div class="col-lg-12">

                                                    <fieldset>
                                                        <textarea name="message" rows="6" id="message"
                                                                  placeholder="Type your comment"
                                                                  required=""></textarea>
                                                    </fieldset>

                                                </div>
                                                <div class="col-lg-12">
                                                    <fieldset>
                                                        <button type="submit" id="form-submit" class="main-button">
                                                            Submit
                                                        </button>
                                                    </fieldset>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% include "includes/sideBar.html" %}
            </div>
        </div>
    </section>
    <script>
        function set_value(id) {
            document.getElementById('id1').value = id
        }
    </script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#like-btn').click(function () {
                const postId = $(this).data('post-id');
                const btn = $(this);

                $.ajax({
                    url: '{% url "blog:like" %}',
                    type: 'POST',
                    data: {
                        'post_id': postId,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function (response) {
                        $('#like-count').text(response.like_count);
                        btn.text(response.liked ? '❤️' : '🤍');
                    }
                });
            });
        });
    </script>
{% endblock %}